# Generated by Django 4.2 on 2023-04-12 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Measure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название мерки')),
                ('description', models.CharField(blank=True, max_length=300, null=True, verbose_name='Описание мерки')),
                ('rating', models.IntegerField(default=100, verbose_name='Рейтинг')),
                ('image', models.ImageField(upload_to='images/measures', verbose_name='фото мерки')),
            ],
        ),
        migrations.CreateModel(
            name='MeasureSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название набора мерок')),
                ('description', models.TextField(blank=True, max_length=300, null=True, verbose_name='Описание набора мерок')),
            ],
        ),
        migrations.CreateModel(
            name='MeasureType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Тип мерки')),
                ('slug', models.SlugField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MeasureSetItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measure', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='measure.measure', verbose_name='Мерка')),
                ('measureSet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='measure.measureset', verbose_name='Набор мерок')),
            ],
        ),
        migrations.CreateModel(
            name='MeasureOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50, verbose_name='Вариант мерки')),
                ('rating', models.IntegerField(verbose_name='Рейтинг')),
                ('measure', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='measure.measure', verbose_name='Мерка')),
            ],
        ),
        migrations.AddField(
            model_name='measure',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='measure.measuretype', verbose_name='Тип мерки'),
        ),
    ]
