# Generated by Django 4.2 on 2023-04-13 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measure', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='measure',
            options={'verbose_name': 'Мерка', 'verbose_name_plural': 'Мерки'},
        ),
        migrations.AlterModelOptions(
            name='measureoption',
            options={'verbose_name': 'Вариант мерки', 'verbose_name_plural': 'Варианты мерок'},
        ),
        migrations.AlterModelOptions(
            name='measureset',
            options={'verbose_name': 'Набор мерок', 'verbose_name_plural': 'Наборы мерок'},
        ),
        migrations.AlterModelOptions(
            name='measuretype',
            options={'verbose_name': 'Тип мерок', 'verbose_name_plural': 'Типы мерок'},
        ),
    ]
