# Generated by Django 4.2 on 2023-04-11 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingmethod',
            name='code',
            field=models.TextField(max_length=20, unique=True, verbose_name='код типа доставки'),
        ),
    ]
