# Generated by Django 4.2 on 2023-04-12 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0006_orderproperty'),
        ('product', '0006_requiredmeasurementset'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('production_order_comment', models.TextField(max_length=300, verbose_name='Комментарий к заказу на производство')),
                ('title', models.CharField(max_length=50, verbose_name='Заказчик')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='order.order', verbose_name='Заказ')),
            ],
        ),
        migrations.CreateModel(
            name='ProductionOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.product', verbose_name='Товар')),
                ('production_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='production.productionorder', verbose_name='Заказ на производство')),
            ],
        ),
    ]
