# Generated by Django 4.2 on 2023-04-12 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttype',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Символьный код'),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Тип товара'),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('title', models.CharField(max_length=150, verbose_name='название')),
                ('rating', models.IntegerField(default=100, verbose_name='Рэйтинг')),
                ('isActive', models.BooleanField(default=True, verbose_name='Активный?')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updatedAt', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('weight', models.IntegerField(default=1000, verbose_name='Вес')),
                ('voluametricWeight', models.IntegerField(default=1000, verbose_name='Объемный вес')),
                ('productionTime', models.TimeField(blank=True, verbose_name='Время на производство')),
                ('gpostCode', models.IntegerField(default=1, verbose_name='Код товара почты грузии')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Базовая цена')),
                ('description', models.TextField(blank=True, max_length=1000, verbose_name='Подробное описание')),
                ('isCounatable', models.BooleanField(default=True)),
                ('availableQuantity', models.IntegerField(default=0, verbose_name='Доступное количество')),
                ('titlePhoto', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='gallery.image', verbose_name='Фото анонса')),
            ],
        ),
    ]
