# Generated by Django 4.2 on 2023-04-12 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.IntegerField(default=100, verbose_name='Рейтинг'),
        ),
    ]
