# Generated by Django 4.2 on 2023-04-12 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('measure', '0001_initial'),
        ('product', '0005_alter_product_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='requiredMeasurementSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measureSet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='measure.measureset', verbose_name='Требуемый набор')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.product', verbose_name='Товар')),
            ],
        ),
    ]
