# Generated by Django 4.2 on 2023-04-13 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_section_subsection'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterModelOptions(
            name='producttype',
            options={'verbose_name': 'Тип товаров', 'verbose_name_plural': 'Типы товаров'},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'verbose_name': 'Раздел товаров', 'verbose_name_plural': 'Разделы товаров'},
        ),
        migrations.AlterModelOptions(
            name='subsection',
            options={'verbose_name': 'Подраздел товаров', 'verbose_name_plural': 'Подразделы товаров'},
        ),
    ]
