# Generated by Django 4.2 on 2023-04-13 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_product_options_alter_producttype_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='subsection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='product.subsection'),
        ),
    ]
