# Generated by Django 4.2 on 2023-05-09 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_product_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('description', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Подробное описание')),
                ('rating', models.IntegerField(default=100, verbose_name='Рейтинг')),
                ('isActive', models.BooleanField(default=True, verbose_name='Активный?')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Базовая цена')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='product.product', verbose_name='Товар')),
            ],
        ),
    ]
