# Generated by Django 4.2 on 2023-04-11 18:51

import address.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=100, verbose_name='Местоположение')),
                ('gpostCode', models.IntegerField(verbose_name='код страны для почты Грузии')),
                ('postcodeFormat', models.TextField(blank=True, max_length=20, verbose_name='Формат индекса')),
                ('phoneLength', models.IntegerField(default=10, verbose_name='Длина номера телефона без кода')),
                ('countryPhoneCode', models.TextField(max_length=5, verbose_name='Телефонный код страны')),
                ('isEU', models.BooleanField(default=True, verbose_name='Входит в ЕС')),
                ('synonims', models.JSONField(default=address.models.synonyms_default, verbose_name='синонимы')),
            ],
        ),
    ]
