# Generated by Django 4.2 on 2023-04-11 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0002_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postCode', models.TextField(max_length=10, verbose_name='Индекс')),
                ('city', models.TextField(max_length=100, verbose_name='Населенный пункт')),
                ('addressLine', models.TextField(max_length=200, verbose_name='Строка адреса')),
                ('firstName', models.TextField(max_length=100, verbose_name='Имя')),
                ('lastName', models.TextField(max_length=100, verbose_name='Фамилия')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='address.location')),
            ],
        ),
    ]
