# Generated by Django 4.2 on 2023-04-13 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0003_billingaddress'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'Адрес', 'verbose_name_plural': 'Адреса'},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name': 'Местоположение', 'verbose_name_plural': 'Местоположения'},
        ),
    ]
