# Generated by Django 4.2 on 2023-05-06 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0004_alter_address_options_alter_location_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingaddress',
            name='location',
            field=models.CharField(max_length=100, verbose_name='Страна'),
        ),
    ]
