# Generated by Django 4.2 on 2023-04-11 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=200, verbose_name='Код статуса')),
                ('title', models.CharField(max_length=50, verbose_name='Статус заказа')),
                ('rating', models.IntegerField(default=100, verbose_name='порядок выдачи')),
                ('color', models.CharField(default='#ffffff', max_length=7, verbose_name='цвет статуса')),
            ],
        ),
        migrations.AlterField(
            model_name='orderpropertytype',
            name='code',
            field=models.CharField(max_length=20, unique=True, verbose_name='код код свойства заказ'),
        ),
        migrations.AlterField(
            model_name='orderpropertytype',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Свойство заказа'),
        ),
    ]
