# Generated by Django 4.2 on 2023-04-11 20:48

from django.db import migrations, models
import django.db.models.deletion
import order.models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0003_billingaddress'),
        ('shipping', '0002_alter_shippingmethod_code'),
        ('order', '0002_orderstatus_alter_orderpropertytype_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderNumber', models.CharField(max_length=10, unique=True, verbose_name='Номер заказа')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updatedAt', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('orderComment', models.TextField(blank=True, max_length=500, null=True, verbose_name='Комментарий к заказу')),
                ('shippingCost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость доставки')),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='address.address', verbose_name='Адресс доставки')),
                ('billingAddress', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='address.billingaddress', verbose_name='Адрес счета')),
                ('orderStatus', models.ForeignKey(default=order.models.get_first_status, on_delete=django.db.models.deletion.PROTECT, to='order.orderstatus')),
                ('shippingMethod', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shipping.shippingmethod', verbose_name='Способ доставки')),
            ],
        ),
    ]
