# Generated by Django 4.2 on 2023-04-13 17:14

from django.db import migrations, models
import django.db.models.deletion
import order.models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_orderproperty'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-orderNumber'], 'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Товар в заказе', 'verbose_name_plural': 'Товары в заказе'},
        ),
        migrations.AlterModelOptions(
            name='orderproperty',
            options={'verbose_name': 'Знаение свойства заказа', 'verbose_name_plural': 'значения свойств заказов'},
        ),
        migrations.AlterModelOptions(
            name='orderpropertytype',
            options={'verbose_name': 'Свойство заказа', 'verbose_name_plural': 'Свойства заказа'},
        ),
        migrations.AlterModelOptions(
            name='orderstatus',
            options={'verbose_name': 'Статус заказа', 'verbose_name_plural': 'Статусы заказа'},
        ),
        migrations.AlterField(
            model_name='order',
            name='orderStatus',
            field=models.ForeignKey(default=order.models.get_first_status, on_delete=django.db.models.deletion.PROTECT, to='order.orderstatus', verbose_name='Статус'),
        ),
    ]
