# Generated by Django 4.2 on 2023-05-06 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Оплачено'),
        ),
        migrations.AlterField(
            model_name='order',
            name='orderNumber',
            field=models.CharField(max_length=10, verbose_name='Номер заказа'),
        ),
    ]
